language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5
    - clang-3.8

install:
  - sudo apt-get update -q
  - sudo apt-get install -y build-essential python3 wget ninja

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

  # meson
  - wget https://github.com/mesonbuild/meson/releases/download/0.30.0/meson_0.30.0.tar.gz
  - tar -xvf meson_0.30.0.tar.gz
  - cd meson-0.30.0
  - sudo python3 setup.py install --prefix=/usr
  - sudo ln -s /usr/bin/meson.py /usr/bin/meson
  - cd ..

script:
  - mkdir build
  - meson build
  - cd build
  - ninja
  - ninja test

notifications:
  email: false
