version: 0.1.{build}

skip_tags: true

os:
  - Windows Server 2012 R2
  - MinGW
  - Visual Studio 2015

build:
  parallel: true
  verbosity: minimal

init:
  - cmd: cmake --version

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: cd ../

test_script:
  - cmd: cd build\bin\Debug
  - cmd: runTest.exe
  - cmd: vTest.exe

deploy: off
